services:
  api1: &api
    image: jrblatt/rinha-2026-rust:v0.0.1
    # image: rinha-fraud-2026:latest
    # build: .
    environment:
      - SOCK=/run/sock/api1.sock
    volumes:
      - sock:/run/sock
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "160M"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    cpuset: "0,1"

  api2:
    <<: *api
    environment:
      - SOCK=/run/sock/api2.sock
    cpuset: "2,3"

  lb:
    image: nginx:1.27-alpine
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - sock:/run/sock
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "30M"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    cpuset: "0,2"

volumes:
  sock:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=4m,mode=0777"
