services:
  api1: &api 
    image: jrblatt/rinha-2026-rust:v0.1.3
    # image: rinha-fraud-2026:latest
    # build: .
    environment:
      - SOCK=/run/sock/api1.sock
    volumes:
      - sock:/run/sock
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "160M"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    security_opt:
      - seccomp:unconfined

  api2:
    <<: *api
    environment:
      - SOCK=/run/sock/api2.sock

  lb:
    image: jrblatt/so-no-forevis:v0.0.1
    restart: always
    depends_on:
      - api1
      - api2
    environment:
      - UPSTREAMS=/run/sock/api1.sock,/run/sock/api2.sock
      - PORT=9999
    ports:
      - "9999:9999"
    volumes:
      - sock:/run/sock
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "30M"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    security_opt:
      - seccomp:unconfined

volumes:
  sock:
