worker_processes 1;
worker_rlimit_nofile 65535;

events {
    worker_connections 1024;
    use epoll;
    multi_accept on;
}

http {
    access_log off;
    error_log /dev/null crit;

    sendfile on;
    tcp_nopush off;
    tcp_nodelay on;

    keepalive_timeout 75s;
    keepalive_requests 100000;

    upstream fraud {
        server unix:/run/sock/api1.sock;
        server unix:/run/sock/api2.sock;
        keepalive 128;
    }

    server {
        listen 9999 reuseport backlog=4096 default_server;

        location / {
            proxy_pass http://fraud;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_buffering off;
            proxy_request_buffering off;
        }
    }
}
